# Site
repository: seongeun1/seongeun1.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Seongeun Stella Park
title: Software Developer
email: galaxypse723@gmail.com
website: https://githubio.seongeun1.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  seongeun1
linkedin_username: stella-seongeun-park-7402b7215

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)


# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Seongeun Stella Park and you can call me Stella!

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KOSCOM
        link: https://www.koscom.co.kr/eng/main.do?mobileYn=Y
        link_text: KOSCOM
        sub_title: Junior Software Developer
        caption: Oct. 2020 - Feb. 2025
        quote: >
          Built core backend systems for Korean and international financial institutions.
        description: | # this will include new lines to allow paragraphs
            - To trade stocks, customers must first open an account. I was responsible for account and customer service operations for both individual and corporate clients, covering every step from account opening and customer registration through all pre-trade processes.
            - I also managed the account opening and maintenance services for tax-advantaged personal pension plans and investment trust funds.
            - Furthermore, I participated in the MyData integrating account inquiry and management across multiple financial institutions and worked on the account-freeze service to guard against phishing and fraud.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Sogang University
        caption: Mar. 2016 – Feb. 2021
        description: |
          - Majored in Economics and Convergence Software Engineering
          - Graduated with a GPA of 3.98/4.5 (≈3.54/4.0)
          - Completed 212 hours of educational volunteer service (Mar.2015 - Nov.2016)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Recently relocated to Atlanta, GA.
      - At Koscom, I worked primarily with properitary platforms and frameworks.
      - Currentary on sabbatical, I'm exploring new technologies through personal projects.
      - Planning to deepen my expertise in database systems.
      
      Outside of work and study, I enjoy:
      - Maintaining a travel blog: blog.naver.com/se_in_the_galazy


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
