

title         : "Invitation from Parks"
name          : "Seongeun Seolleun Park" 
description   : "Wedding Invitation"
url           : "https://seongeun1.github.io" # the base hostname & protocol for your site

teaser        : "/img/main2.jpg"
og_image      : "/img/main2.jpg"

repository    : "seongeun1/comments"
author        : Seongeun


# Site Author
author:
  name             : "Seongeun Seolleun Park"
  avatar           : "/img/UND_0248.JPG"
  bio              : "흠"
  location         : "Republic of Korea"
  email            : "galaxypse723@gamil.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:galaxypse723@gamil.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.naver.com/se_in_the_galaxy"



# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/seongeun1"

# Outputting
permalink: /:categories/:title/
paginate: 1 # 첫 페이지에보여줄 최근 게시물 수를 지정
paginate_path: /page:num/
timezone: Asia/Seoul # 


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false


# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html


#change your port on localhost
port: 8000


